#!/bin/bash

##
# Simple script to perform export a DS plugin to zip.
#
# You can use this lovely little script to export your DroidScript
# JS only plugin source files from a git repo into a zip.
#


##
# Describes correct usage of the script
#
usage() {
  echo 'Usage: export <SrcFolder> <ProjectName> <branch>'
  echo ' '
  echo 'Use to export DS JS only plugin src files from the project into zip.'
  exit 1
}

#
# Check for correct number of args
#
if [[ $# -ne 3 ]]; then
  usage
fi

target="./dist"

if [[ ! -d $target ]]; then
  mkdir $target
fi

args=("$@")
##
# Extract the archive to a zip file
#
git archive --format zip --output $target/${args[1]}.zip ${args[2]}:${args[0]}

##
# Extract the .zip to a folder and then compress that as a .zip and change
# the extension to .spk
#
# cd $target

# unzip ${args[1]}.zip -d ${args[1]}

# rm ${args[1]}.zip

# zip -r  ${args[1]}.zip ${args[1]}

# mv ${args[1]}.zip ${args[1]}.spk

# rm -R ${args[1]}

echo "------------------------------------------------------------"
echo "Export complete! Exported to: ${args[1]}.zip"

exit 0
