#!/bin/bash

##
# Simple script to perform export a DS plugin to zip.
#
# You can use this lovely little script to export your DroidScript
# JS only plugin source files from a git repo into a zip.
#


##
# Describes correct usage of the script
#
usage() {
  printf "%s\n\n" 'Usage: export <SrcFolder> <ProjectName> <branch>'
  printf "%s\n\n" echo'Use to export DS JS only plugin src files from the project into zip.'
  exit 1
}

#
# Check for correct number of args
#
if [[ $# -ne 3 ]]; then
  usage
fi

target="./dist"

if [[ ! -d $target ]]; then
  mkdir $target
fi

args=("$@")

##
# Extract the git archive to a zip file in the target folder
#
git archive --format zip --output $target/${args[1]}.zip ${args[2]}:${args[0]}

echo "------------------------------------------------------------"
echo "Export complete! Exported to: ${args[1]}.zip"

exit 0
